### ISSUE TITLE
Request for Assistance: Issue with MODIS File Structure in VPRM Input Creation

### ISSUE THREAD

**Issue by ghost** [rnoeliab/WRF-GHG-Prepy#1]
I have followed the instructions you provided for creating VPRM input and downloaded the necessary MODIS images for my region of interest:
hvs: 
 - [31,9]
 
However, when I run the script, I encounter the following issue:

# ----------------------------------------------------------------------------------------------------------------------------------------
(pyvprm_env) sanazm@DESKTOP-3SK4L7M:~/WRF/WRF-GHG-Prepy/pyVPRM/pyVPRM_examples/wrf_preprocessor$ python vprm_preprocessor_new.py --year 2022 --config ./config/preprocessor_config.yaml
Namespace(config='./config/preprocessor_config.yaml', year=2022, n_cpus=1, chunk_x=1, chunk_y=1)
[[31 10]
 [32 10]]
[31 10]
2024-10-20 10:06:59.242 | INFO     | pyVPRM.VPRM:__init__:60 - Running with pyVPRM version 3.0
./data/modis/netcdf_files/correct_format/MOD09A1.A2022081.h31v10.061.2022097045439_crop.nc
Traceback (most recent call last):
  File "/home/sanazm/WRF/WRF-GHG-Prepy/pyVPRM/pyVPRM_examples/wrf_preprocessor/vprm_preprocessor_new.py", line 81, in <module>
    handler.load()
  File "/home/sanazm/miniconda3/envs/pyvprm_env/lib/python3.9/site-packages/pyVPRM/sat_managers/base_manager.py", line 157, in load
    self.individual_loading(**kwargs)
  File "/home/sanazm/miniconda3/envs/pyvprm_env/lib/python3.9/site-packages/pyVPRM/sat_managers/modis.py", line 221, in individual_loading
    self.sat_img = self.sat_img.assign_coords({"time": self.get_recording_time()})
  File "/home/sanazm/miniconda3/envs/pyvprm_env/lib/python3.9/site-packages/pyVPRM/sat_managers/modis.py", line 235, in get_recording_time
    self.meta_data["RANGEBEGINNINGDATE"]
KeyError: 'RANGEBEGINNINGDATE'
(pyvprm_env) sanazm@DESKTOP-3SK4L7M:~/WRF/WRF-GHG-Prepy/pyVPRM/pyVPRM_examples/wrf_preprocessor$
# ----------------------------------------------------------------------------------------------------------------------------------------

I believe the issue lies with the MODIS files. When I compared one of your MODIS files in the /WRF-GHG-Prepy/pyVPRM/pyVPRM_examples/wrf_preprocessor/data/modis/ directory with mine, I noticed structural differences, although I followed the instructions and downloaded them the same way. I will share one of the MODIS files I downloaded.

Could you kindly assist me in resolving this issue?

[MODIS_File.txt](https://github.com/user-attachments/files/17449425/MODIS_File.txt)

**Comment by rnoeliab** [comment]
Hi, 
I'm sorry I haven't responded, I did not notice the message. I'd like to know if you've been able to solve the problem, if not. I'll be uploading some documents in the github that you should follow, another thing before running "vprm_preprocessor_new.py" it is necessary to do an exercise,  open in the terminal (within the environment):

>> python
>> import rioxarray
>> ds = rioxarray.open_rasterio("MOD09A1.A2020049.h08v11.061.hdf")

**Comment by Oak-nut** [comment]
Thanks for sharing the WRF_GHG_PrepPy whole process.
And I would like to ask if my understanding of the module operating procedure is correct?

- WRF_GHG_PrepPy: 
Processing of raw emission inventories
Spatial allocation to the WRF grid
Time decomposition to simulation time step

- Process the WRF model with ./real.exe ./wrf.exe and set the chem_opt = 17

- Input the file obtained from WRF_GHG_PrepPy module, and analysis the result

Looking forward to your reply, thanks again.

**Comment by rnoeliab** [comment]
RUN THE REAL./EXE TO OBTAIN THE WRFINPUTS AND WRFBDY FILES (DIRECT THESE FILES IN A PASTE WHERE THE GEO_EMD SHOULD ALSO BE). 
THEN YOU CAN RUN THE WRF-GHG-PREPPY TO JOIN THE INPUTS DATA FROM INVENTORIES. 
1. ANTHO
2. BIOGENIC
3. FIRES
4. BACKGROUND
IN THE BACKGROUND FIELD, THERE IS A SUB-PROCESS TO FILL WRFINPUTS AND WRFBDY FILES. 
FINALLY, RUN THE WRF.EXE

**Comment by Oak-nut** [comment]
> RUN THE REAL./EXE TO OBTAIN THE WRFINPUTS AND WRFBDY FILES (DIRECT THESE FILES IN A PASTE WHERE THE GEO_EMD SHOULD ALSO BE). THEN YOU CAN RUN THE WRF-GHG-PREPPY TO JOIN THE INPUTS DATA FROM INVENTORIES.
> 
> 1. ANTHO
> 2. BIOGENIC
> 3. FIRES
> 4. BACKGROUND
>    IN THE BACKGROUND FIELD, THERE IS A SUB-PROCESS TO FILL WRFINPUTS AND WRFBDY FILES.
>    FINALLY, RUN THE WRF.EXE

In the introduction, u mentioned that the third part is "III. Finally run the "prep_initial" and "prep_boundary" script.". This means that I should run the scripts in pys file?
including:
          Join_vprm_input.py
          ptrp_cpool_lpj.py
          prep_edgar,py
          prep_gfas.py
          prep_T-ann.py
          prep_wetland_kaplan.py
to prepare the boundary?
Thanks for reply.

**Comment by rnoeliab** [comment]
> > RUN THE REAL./EXE TO OBTAIN THE WRFINPUTS AND WRFBDY FILES (DIRECT THESE FILES IN A PASTE WHERE THE GEO_EMD SHOULD ALSO BE). THEN YOU CAN RUN THE WRF-GHG-PREPPY TO JOIN THE INPUTS DATA FROM INVENTORIES.
> > 
> > 1. ANTHO
> > 2. BIOGENIC
> > 3. FIRES
> > 4. BACKGROUND
> >    IN THE BACKGROUND FIELD, THERE IS A SUB-PROCESS TO FILL WRFINPUTS AND WRFBDY FILES.
> >    FINALLY, RUN THE WRF.EXE
> 
> In the introduction, u mentioned that the third part is "III. Finally run the "prep_initial" and "prep_boundary" script.". This means that I should run the scripts in pys file? including: Join_vprm_input.py ptrp_cpool_lpj.py prep_edgar,py prep_gfas.py prep_T-ann.py prep_wetland_kaplan.py to prepare the boundary? Thanks for reply.

Hi,
run "prep_initial and boundary scripts means that you must run the scripts pys files, mainly prep_initial and boundary". The other scripts (Join_vprm_input.py ptrp_cpool_lpj.py prep_edgar,py prep_gfas.py prep_T-ann.py prep_wetland_kaplan.py) are for preparing the emission inputs.
